# Generated by Django 4.2.4 on 2023-09-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Invest", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
    ]
